spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_system?createDatabaseIfNotExist=true
    username: root
    password: 7392
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
